name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        wget --no-check-certificate https://www.math.ucdavis.edu/~latte/software/packages/binary/latte-integrale-1.6-x86_64-unknown-linux-gnu.zip -O /tmp/latte.zip
        mkdir latte && pushd latte && unzip /tmp/latte.zip && popd
        export LATTE_PATH=$PWD/latte/bin/count
    - name: Install barvikron package
      run: |
        python -m pip install --upgrade pip
        python -m pip install .[dev]
    - name: Compute one coefficient
      run: |
        barvikron [20,0] [11,9] [11,9] --latte=$LATTE_PATH
    - name: Test with pytest
      run: |
        pytest --latte=$LATTE_PATH
