name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install LaTTE
      run: |
        wget --no-check-certificate https://www.math.ucdavis.edu/~latte/software/packages/binary/latte-integrale-1.6-x86_64-unknown-linux-gnu.zip -O /tmp/latte.zip
        mkdir latte && pushd latte && unzip /tmp/latte.zip && popd
        ls /home/runner/work/barvikron/barvikron/latte/bin/count
        ls latte/bin/count
    - name: Install package
      run: |
        python -m pip install --upgrade pip
        python -m pip install .[dev]
    - name: Compute one coefficient
      run: |
        barvikron [20,0] [11,9] [11,9] --latte=/home/runner/work/barvikron/barvikron/latte/bin/count
    - name: Test with pytest
      run: |
        pytest --latte=/home/runner/work/barvikron/barvikron/latte/bin/count
